version: "3"

services:
  prisma:
    image: prismagraphql/prisma:1.34
    # container_name: "prisma"
    restart: always
    
    # Uncomment for open ports
    # ports:
      # - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: ${MYSQL_HOST:-mysql}
            port: ${MYSQL_PORT:-3306}
            database: ${MYSQL_DB}
            user: ${MYSQL_USER:-root}
            password: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Can set another path 
      - mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST:-mysql}
      PMA_PORT: ${MYSQL_PORT:-3306}
    depends_on:
      - mysql

  front:
    # image: abiosoft/caddy
    tty: true
    restart: always
    environment:
      # - CADDYPATH=/etc/certs
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./caddy/Caddyfile:/etc/Caddyfile
      - ./certs:/etc/certs
      # - .:/app
    # depends_on:
      # - pma
      # - api
    build:
      context: ./caddy

volumes:
  mysql:
