version: "3.7"

services:

  front:
    command: bash -c "yarn build && yarn start-ssr"

  api:
    command: bash -c "echo $endpoint && yarn deploy && yarn start-server"

  proxy:
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
