version: "3.7"

services:

  prisma:
    ports:
      - '4466:4466'

  front:
    volumes:
      - ./prisma-cms/boilerplate/src:/www/boilerplate/src
    command: yarn start

  api:
    volumes:
      - ./prisma-cms/boilerplate/src:/www/boilerplate/src
    environment: 
      - SendmailTest=true
    command: "yarn start-server-dev"

  proxy:
    ports:
      - 2015:2015
      - 2016:2016
      - 2017:2017
